# -*- coding: utf-8 -*-
"""prepare_data_for_portfolio.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1El3nALUCnNnVLpL_YyrVkkmZB8fTYzmw
"""

import pandas as pd
import datetime

"""### EOD data for USD"""

USD_predicted_data = pd.read_csv('./USD_10min_predicted_price.csv')
USD_data = pd.read_csv('./USD_10min_dataset.csv')

USD_predicted_data = USD_predicted_data.drop(['y_train'], axis=1)
USD_predicted_data['Date'] = pd.to_datetime(USD_predicted_data['Date'])
USD_predicted_data = USD_predicted_data.dropna()
USD_predicted_data = USD_predicted_data.sort_values(['Date', 'y_pred']).groupby(USD_predicted_data['Date'].dt.date)['y_pred'].agg(['last']).reset_index()
USD_predicted_data.head()

USD_data['Date'] = pd.to_datetime(USD_data['Date'], errors='coerce')
USD_data=USD_data.sort_values(by="Date", ascending=True)
USD_data = USD_data.dropna()
USD_data = USD_data.sort_values(['Date', 'Close']).groupby(USD_data['Date'].dt.date)['Close'].agg(['last']).reset_index()
USD_data = USD_data.loc[USD_data['Date'] <= datetime.date(year=2022,month=8,day=21)]

USD_data_merged = pd.concat([USD_data, USD_predicted_data])
USD_data_merged.columns=['Date','USD']

USD_data_merged_D = USD_data_merged[USD_data_merged.duplicated()==True]
USD_data_merged_D

USD_data_merged

#USD_data_merged.set_index('Date',inplace=True)

"""### EOD data for Binance"""

binance_predicated_data = pd.read_csv('./binance_10min_predicted_price.csv')
binance_data = pd.read_csv('./binance_10min_dataset.csv')

binance_predicated_data = binance_predicated_data.drop(['y_train'], axis=1)
binance_predicated_data['Date'] = pd.to_datetime(binance_predicated_data['Date'])
binance_predicated_data = binance_predicated_data.dropna()
binance_predicated_data = binance_predicated_data.sort_values(['Date', 'y_pred']).groupby(binance_predicated_data['Date'].dt.date)['y_pred'].agg(['last']).reset_index()
#binance_data.set_index('Date',inplace=True)

binance_predicated_data.head()

binance_data['Date'] = pd.to_datetime(binance_data['Date'], errors='coerce')
binance_data=binance_data.sort_values(by="Date", ascending=True)
binance_data = binance_data.dropna()
binance_data = binance_data.sort_values(['Date']).groupby(binance_data['Date'].dt.date)['Close'].agg(['last']).reset_index()
binance_data = binance_data.loc[binance_data['Date'] <= datetime.date(year=2022,month=8,day=21)]

binance_data.head()

binance_data_merged = pd.concat([binance_data, binance_predicated_data])
binance_data_merged.columns=['Date','binance']

binance_data_merged_d = binance_data_merged[binance_data_merged.duplicated()==True]
binance_data_merged_d

binance_data_merged

"""### EOD data for Bitcoin"""

bitcoin_predicated_data = pd.read_csv('./bitcoin_10min_predicted_price.csv')
bitcoin_data = pd.read_csv('./bitcoin_10min_dataset.csv')

bitcoin_predicated_data = bitcoin_predicated_data.drop(['y_train'], axis=1)
bitcoin_predicated_data['Date'] = pd.to_datetime(bitcoin_predicated_data['Date'])
bitcoin_predicated_data = bitcoin_predicated_data.dropna()
bitcoin_predicated_data = bitcoin_predicated_data.sort_values(['Date', 'y_pred']).groupby(bitcoin_predicated_data['Date'].dt.date)['y_pred'].agg(['last']).reset_index()
#bitcoin_data.set_index('Date',inplace=True)

bitcoin_predicated_data.head()

bitcoin_data['Date'] = pd.to_datetime(bitcoin_data['Date'], errors='coerce')
bitcoin_data=bitcoin_data.sort_values(by="Date", ascending=True)
bitcoin_data = bitcoin_data.dropna()
bitcoin_data = bitcoin_data.sort_values(['Date']).groupby(bitcoin_data['Date'].dt.date)['Close'].agg(['last']).reset_index()
bitcoin_data = bitcoin_data.loc[(bitcoin_data['Date'] >= datetime.date(year=2022,month=3,day=11)) & (bitcoin_data['Date'] <= datetime.date(year=2022,month=8,day=23))]

bitcoin_data_merged = pd.concat([bitcoin_data, bitcoin_predicated_data])
bitcoin_data_merged.columns=['Date','bitcoin']

bitcoin_data_merged_d = bitcoin_data_merged[bitcoin_data_merged.duplicated()==True]
bitcoin_data_merged_d

bitcoin_data_merged

"""### EOD data for Ethereum"""

ethereum_predicated_data = pd.read_csv('./ethereum_10min_predicted_price.csv')
ethereum_data = pd.read_csv('./ethereum_10min_dataset.csv')

ethereum_predicated_data = ethereum_predicated_data.drop(['y_train'], axis=1)
ethereum_predicated_data['Date'] = pd.to_datetime(ethereum_predicated_data['Date'])
ethereum_predicated_data = ethereum_predicated_data.dropna()
ethereum_predicated_data = ethereum_predicated_data.sort_values(['Date', 'y_pred']).groupby(ethereum_predicated_data['Date'].dt.date)['y_pred'].agg(['last']).reset_index()
#ethereum_data.set_index('Date',inplace=True)

ethereum_predicated_data

ethereum_data['Date'] = pd.to_datetime(ethereum_data['Date'], errors='coerce')
ethereum_data=ethereum_data.sort_values(by="Date", ascending=True)
ethereum_data = ethereum_data.dropna()
ethereum_data = ethereum_data.sort_values(['Date']).groupby(ethereum_data['Date'].dt.date)['Close'].agg(['last']).reset_index()
ethereum_data = ethereum_data.loc[(ethereum_data['Date'] >= datetime.date(year=2022,month=3,day=11)) & (ethereum_data['Date'] <= datetime.date(year=2022,month=8,day=23))]

ethereum_data_merged = pd.concat([ethereum_data, ethereum_predicated_data])
ethereum_data_merged.columns=['Date','ethereum']

ethereum_data_merged_d = ethereum_data_merged[ethereum_data_merged.duplicated()==True]
ethereum_data_merged_d

ethereum_data_merged

"""### EOD data for Tether"""

tether_predicated_data = pd.read_csv('./tether_10min_predicted_price.csv')
tether_data = pd.read_csv('./tether_10mins_dataset.csv')

tether_predicated_data = tether_predicated_data.drop(['y_train'], axis=1)
tether_predicated_data['Date'] = pd.to_datetime(tether_predicated_data['Date'])
tether_predicated_data = tether_predicated_data.dropna()
tether_predicated_data = tether_predicated_data.sort_values(['Date', 'y_pred']).groupby(tether_predicated_data['Date'].dt.date)['y_pred'].agg(['last']).reset_index()
#tether_data.set_index('Date',inplace=True)

tether_predicated_data.head()

tether_data['Date'] = pd.to_datetime(tether_data['Date'], errors='coerce')
tether_data=tether_data.sort_values(by="Date", ascending=True)
tether_data = tether_data.dropna()
tether_data = tether_data.sort_values(['Date']).groupby(tether_data['Date'].dt.date)['Close'].agg(['last']).reset_index()
tether_data = tether_data.loc[(tether_data['Date'] >= datetime.date(year=2022,month=3,day=11)) & (tether_data['Date'] <= datetime.date(year=2022,month=8,day=23))]

tether_data_merged = pd.concat([tether_data, tether_predicated_data])
tether_data_merged.columns=['Date','tether']

tether_data_merged_d = tether_data_merged[tether_data_merged.duplicated()==True]
tether_data_merged_d

tether_data_merged

"""### Merge All Dataframe"""

crypto_predicated_data_1 = pd.merge(USD_data_merged,ethereum_data_merged, how='inner',on ='Date')
crypto_predicated_data_2 = pd.merge(crypto_predicated_data_1,binance_data_merged, how='inner',on ='Date')
crypto_predicated_data_3 = pd.merge(crypto_predicated_data_2, bitcoin_data_merged, how='inner',on ='Date')
crypto_predicated_data_4 = pd.merge(crypto_predicated_data_3,tether_data_merged, how='inner',on ='Date')

crypto_predicated_data_4.columns = ['Date','USD','ethereum','binance','bitcoin','tether']
crypto_predicated_data_4.to_csv('Crypto_predicted_close_price.csv')
crypto_predicated_data_4

crypto_predicated_data_4.set_index('Date',inplace=True)

crypto_predicated_data_4.to_csv('./crypto_predicted_close_price.csv')