# -*- coding: utf-8 -*-
"""Hierarchical_Risk_Parity.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gjKT708UedQaoa-3bK2BGPn8iG7drsZy
"""

#!pip install PyPortfolioOpt
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pypfopt
from pypfopt import expected_returns
from pypfopt import HRPOpt



data = pd.read_csv('./crypto_predicted_close_price.csv')
data.set_index('Date',inplace=True)
data.drop('Unnamed: 0', axis=1, inplace=True)  
data.sort_index(inplace=True)

rets = expected_returns.returns_from_prices(data)
rets.tail()

hrp = HRPOpt(rets)
hrp.optimize()
weights = hrp.clean_weights()
weights

pd.Series(weights).plot.pie(figsize=(10, 10));

hrp.portfolio_performance(verbose=True);

from pypfopt import plotting

plotting.plot_dendrogram(hrp);